[package]
name = "pumpkin-util"
version.workspace = true
edition.workspace = true

[dependencies]
pumpkin-nbt = { path = "../pumpkin-nbt" }
serde.workspace = true
serde_json.workspace = true
bytes.workspace = true

num-traits = "0.2"

colored = "3.0"
md5 = "0.7"
